### ISSUE TITLE
Keyboard.removeListener is not a function for SearchBar

### ISSUE THREAD

**Issue by kvntzn** [react-native-elements/react-native-elements#3206]
**Explain what you did (Required)**

Upgrade react native version from v0.63.4 to v0.65.1

**Expected behavior (Required)**

app should not crash

**Describe the bug (Required)**

App crashes after upgrading the version for SearchBar with platform=android

**To Reproduce (Required)**

**Screenshots (Required)**
Example:
![Screenshot_1632145766](https://user-images.githubusercontent.com/29770932/134014261-95695836-fa4c-4f91-ae3d-775065332e9e.png)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |  3.4.2       |
| react-native          |  0.65.1       |

**Comment by ggpereira** [comment]
Hey, sorry for my bad english, I got the same error after upgrade react-native to 0.65.1. I found the temporarly solution for this in this issue:  https://github.com/FaridSafi/react-native-gifted-chat/issues/2090. 

I believe which this library is not compatible with latest version of react native. 

my solution was modify file SearchBar-android.js as next

![Captura de tela 2021-09-22 162944](https://user-images.githubusercontent.com/26494904/134409526-666650bc-12bf-4116-8236-e8c31a47a0b1.png)



I hope this will be fixed soon by the maintainers.

**Comment by kvntzn** [comment]
> Hey, sorry for my bad english, I got the same error after upgrade react-native to 0.65.1. I found the temporarly solution for this in this issue: [FaridSafi/react-native-gifted-chat#2090](https://github.com/FaridSafi/react-native-gifted-chat/issues/2090).
> 
> I believe which this library is not compatible with latest version of react native.
> 
> my solution was modify file SearchBar-android.js as next
> 
> ![Captura de tela 2021-09-22 162944](https://user-images.githubusercontent.com/26494904/134409526-666650bc-12bf-4116-8236-e8c31a47a0b1.png)
> 
> I hope this will be fixed soon by the maintainers.

Thanks, this works. I hope so too.

**Comment by arpitBhalla** [comment]
This has been resolved by #3215

**Comment by vinnybad** [comment]
I chose this approach rather than modifying react-native-elements. It might be useful for someone.

```
import { Keyboard } from "react-native";

/**
 * https://github.com/react-native-elements/react-native-elements/issues/3206
 * 
 * Keyboard.removeListener is no longer a method in newer RN. This provides a
 * polyfill that internally removes all listeners. This might not be suitable
 * for every project, but it fixes the error mentioned above.
 */
export function provideRemoveListenerPolyfill() {
    // @ts-ignore
    Keyboard.removeListener = (eventType, listener) => {
        Keyboard.removeAllListeners(eventType);
    };
}
```

**Comment by damardones** [comment]
> y solution was modify file SearchBar-android.js a

Thanks its guide me to solve my issue. I just replace the call to keyboard.removeListener for keyboard.removeAllListener
