### ISSUE TITLE
ListItem: Typescript error with @types/react-native >= 0.65.7

### ISSUE THREAD

**Issue by renchap** [react-native-elements/react-native-elements#3227]
**Explain what you did (Required)**

Upgraded `@types/react-native` to version `0.65.8`

**Expected behavior (Required)**

No type errors happen

**Describe the bug (Required)**

I am now getting this typescript error:
```
error TS2739: Type '{ children: Element[]; bottomDivider: boolean; disabled: boolean | undefined; onPress: (() => void) 
| undefined; }' is missing the following properties from type 'Pick<TouchableHighlightProps & { containerStyle?: 
StyleProp<ViewStyle>; disabledStyle?: StyleProp<ViewStyle>; ... 6 more ...; children?: any; } & Partial<...>, 
"children" | ... 45 more ... | "bottomDivider">': hasTVPreferredFocus, tvParallaxProperties

20     <ListItem
        ~~~~~~~~
```

This is probably caused by the change in this PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56374 (worked with 0.65.6, error appeared with 0.65.7).

**To Reproduce (Required)**

Just use a simple `<ListItem>` in a RN project with Typescript.

**Screenshots (Required)**

Not required here

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     3.4.2    |
| react-native          |    0.66.1     |
| @types/react-native          |    0.65.8     |

**Comment by cbotsikas** [comment]
I also have the same issue with `hasTVPreferredFocus`, `tvParallaxProperties` and `autoCompleteType`

lib | version
-- | --
react-native-elements | 3.4.2
@types/react-native | 0.66.1
react-native | 0.66.1

On a `ListItem` from `react-native-elements`:
```
error TS2739: Type '{ children: Element[]; containerStyle: { alignContent: "space-around"; alignItems: "stretch"; backgroundColor: string; borderColor: string; borderRadius: number; borderWidth: number; flex: number; flexDirection: "column"; paddingHorizontal: number; paddingVertical: number; }; }' is missing the following properties from type 'Pick<TouchableHighlightProps & { containerStyle?: StyleProp<ViewStyle>; disabledStyle?: StyleProp<ViewStyle>; ... 6 more ...; children?: any; } & Partial<...>, "testID" | ... 45 more ... | "bottomDivider">': hasTVPreferredFocus, tvParallaxProperties
```

On an `Input` from `react-native-elements`
```
error TS2741: Property 'autoCompleteType' is missing in type '{ value: string | undefined; placeholderTextColor: string; inputStyle: { fontWeight: "bold"; color: string; fontSize: number; paddingLeft: number; }; placeholder: string; leftIcon: Element; containerStyle: { ...; }; inputContainerStyle: { ...; }; onChangeText: (inputValue: string) => void; }' but required in type 'Pick<TextInputProps & RefAttributes<TextInput> & { containerStyle?: StyleProp<ViewStyle>; disabled?: boolean | undefined; ... 14 more ...; renderErrorMessage?: boolean | undefined; } & Partial<...>, "testID" | ... 125 more ... | "renderErrorMessage">'.
```

**Comment by moriax** [comment]
Hello,
is there any workarround/manual patch possible ?
When is it expected to get it officially fixed ?

**Comment by 29er** [comment]
I need a workaround for this if I can continue using this lib. please ! thanks

**Comment by renchap** [comment]
Using the bleeding edge version of `react-native-elements` (see https://reactnativeelements.com/docs#bleeding-edge) fixes the error.

@flyingcircle can we have a release of the package so it fixes it without having to rely on the git version? 🙇

**Comment by flyingcircle** [comment]
@renchap  I'm still putting out fires at work due to this log4j thing. But I'll see if I can do a quick release sometime this week.

**Comment by kickbk** [comment]
+1

**Comment by nikola166** [comment]
+1

**Comment by renchap** [comment]
Beta version for 4.0.0 has been released and it fixes this issue, you can use it like this in your `package.json`:

```json
{
  "dependencies": {
    "react-native-elements": "^4.0.0-beta.0",
  }
}

```

**Comment by darkbasic** [comment]
I've found a small bug in 4.0:
```
export const getTheme = (isDark: boolean): Partial<FullTheme> => {
  const colors = getColors(isDark);
  return {
    ListItem: {
      containerStyle: {
        backgroundColor: colors.whiteGrey0,
      },
      underlayColor: colors.whiteGrey0,
    },
  };
};
```

```
src/theme/AppTheme.tsx:235:7 - error TS2322: Type '{ containerStyle: { backgroundColor: string; }; underlayColor: string; }' is not assignable to type 'Partial<ListItemProps>'.
  Object literal may only specify known properties, and 'containerStyle' does not exist in type 'Partial<ListItemProps>'.

235       containerStyle: {
          ~~~~~~~~~~~~~~~~~
236         backgroundColor: colors.whiteGrey0,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
237       },
    ~~~~~~~

  node_modules/react-native-elements/dist/config/theme.d.ts:69:5
    69     ListItem: Partial<ListItemProps>;
           ~~~~~~~~
    The expected type comes from property 'ListItem' which is declared here on type 'Partial<FullTheme>'
```

**Comment by jkoutavas** [comment]
I too am having problems with `4.0.0-beta.0`, getting a `Property 'underlayColor' does not exist on type 'IntrinsicAttributes & Omit<PressableProps & { containerStyle?: StyleProp<ViewStyle>; disabledStyle` error on using ListItem's `underlayColor` property:

```ts
    <ListItem
      containerStyle={styles.listItem}
      underlayColor="transparent"
      activeOpacity={0.3}
      onPress={(route || onNavigate) && onNavigationPress}
      {...listItemProps}
    >
```

I'm on React Native 0.66.4

**Comment by Seanmclem** [comment]
rather than use a bleeding edge beta, I just did like @foush said and put these on the components having the error, for now

```
      hasTVPreferredFocus={undefined}
      tvParallaxProperties={undefined}
```

**Comment by ChillyHoney** [comment]
A simple solution which worked for me was to change import of react native elements.
From:
`import { Icon } from 'react-native-elements';`
To:
`import Icon from 'react-native-vector-icons/MaterialCommunityIcons';`

**Comment by RickoNoNo3** [comment]
Although a bit amazing:

I upgraded the version to `4.0.0-beta.0`, or even` 4.0.0-rc.2`, the problem was not fixed(for `Icon` components). But!! I retreated to `3.4.2`, and then the error automatically disappeared. You know, what I had before was just `3.4.2`...

I just edit the version in `package.json`, and run `yarn install`, and edit the version back, and run again. You may also try it.
