### ISSUE TITLE
Using JEST with react-native-elements - mockModal is not a function

### ISSUE THREAD

**Issue by Bilal-Abdeen** [react-native-elements/react-native-elements#3304]
The code below works fine if I use `<Text>` from `react-native`. If I use the `react-native-elements` version, I get the following error message. 

Code: 
```javascript 
import React from "react";
import { render } from "@testing-library/react-native"
import { test } from "@jest/globals"

// import { Text, } from "react-native";
// Using the following statement, instead of the above causes an error!!??
import { Text } from "react-native-elements"; 

const Example = () => {
  	return <Text>Submit</Text>;
};

test("renders correctly", async () => {
  const { getByText } = render(<Example />, ); 
  getByText(/submit/i); 
}) 
```

1st Error:  
```
  ● Test suite failed to run

    Jest encountered an unexpected token
    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.
    By default "node_modules" folder is ignored by transformers.
    Here's what you can do:
...
...
    Details:
    C:\react\testingLibrary\node_modules\react-native-elements\dist\index.js:6
    import Button from './buttons/Button';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

To fix the error above, I added the following line to the `jest.config.js` file. 
```javascript
transformIgnorePatterns: ['node_modules/(?!(jest-)?@react-native|react-native|react-native-elements/*)',],
```

This got rid of the error above. However, now, I am getting the following error message. 
```
  ● Test suite failed to run

    TypeError: mockModal is not a function

      at node_modules/react-native/jest/setup.js:116:12
      at Object.<anonymous> (node_modules/react-native/jest/mockModal.js:16:15)
      at node_modules/react-native/jest/setup.js:115:28
```

**_How can I fix this error?_** 

**My Environment:**

| software              | version |
| --------------------- | ------- |
| react-native | 0.67.0 | 
| react-native-elements | 3.4.2 | 
| @testing-library/jest-native | 4.0.4 | 
| @testing-library/react-native | 9.0.0 | 
| jest | 27.4.7 | 
| metro-react-native-babel-preset | 0.66.2 | 
| react-test-renderer | 17.0.2 | 
| @babel/core | 7.16.7 | 
| @babel/runtime | 7.16.7 | 
| babel-jest | 27.4.6 | 

### Update: 
The problem could be temporarily fixed by downgrading react-native to `0.66.4`

**Comment by eliw00d** [comment]
I can confirm the same thing after upgrading to 0.67.1. The same tests passed with 0.66.4.

**Comment by arpitBhalla** [comment]
Can you confirm this with v4 beta

**Comment by Bilal-Abdeen** [comment]
@arpitBhalla Thank you so much for looking into this so promptly. It works fine with `react-native-elements` version `4.0.0-beta.0`. Great!!!

**Comment by eliw00d** [comment]
@arpitBhalla Any chance this could be fixed with a patch for 3.4.x? We usually try to avoid alpha/beta versions due to changing APIs and such.

**Comment by alaintalk** [comment]
wow thanks for this but it should be just patched on 3.4 instead of manually changing the beta version

**Comment by eliw00d** [comment]
Turns out this is actually a regression in 0.67.x and a workaround has been provided there that solves it without the need to upgrade to 4.0.0.beta-0 for me: https://git.target.com/batphone/studioconnect/pull/3449

**Comment by arpitBhalla** [comment]
Hopefully it would work with latest release

**Comment by cecicifu** [comment]
Similar issue using `4.0.0-rc.6`  😯

![image](https://user-images.githubusercontent.com/15237067/185242312-b3e36d97-d59b-4724-bacc-46246048bc7a.png)

![image](https://user-images.githubusercontent.com/15237067/185242234-84c3219d-d8ab-4dfc-9043-55581f4c53f2.png)

If I add `@rneui` to `transformIgnorePatterns` jest option

![image](https://user-images.githubusercontent.com/15237067/185253318-844eb553-31e0-4bde-bc22-16a9d44c671b.png)

Get these errors

![Screenshot_1](https://user-images.githubusercontent.com/15237067/185253912-d84535f4-c590-45ff-a4d4-7cd972c08d55.png)

**Comment by Pkcarreno** [comment]
@cecicifu same here, did you get why this happens? I'm on 4.0.0-rc.7
